# Dependabot configuration
# <https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates>

version: 2
updates:
  # Bun (bun.lock)
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
      prefix-development: "chore"
      include: "scope"
    groups:
      bun:
        patterns:
          - "*"
      bun-security:
        applies-to: "security-updates"
        patterns:
          - "*"
    cooldown:
      default-days: 5
    ignore:
      # Ignore updates to obsidian beyond 1.4.11
      - dependency-name: "obsidian"
        versions: [">1.4.11"]
      - dependency-name: "@polyipseity/obsidian"
        versions: [">1.4.11"]

  # GitHub Actions (workflow dependencies)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
      prefix-development: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"
    cooldown:
      default-days: 5

  # Git submodules (gitmodules)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
      prefix-development: "chore"
      include: "scope"
    groups:
      gitsubmodule:
        patterns:
          - "*"
      gitsubmodule-security:
        applies-to: "security-updates"
        patterns:
          - "*"
    cooldown:
      default-days: 5

  # Python (pyproject.toml)
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
      prefix-development: "chore"
      include: "scope"
    groups:
      uv:
        patterns:
          - "*"
      uv-security:
        applies-to: "security-updates"
        patterns:
          - "*"
    cooldown:
      default-days: 5
    exclude-paths:
      # wtf: <https://github.com/dependabot/dependabot-core/issues/13960>
      - "LICENSE.txt"
    ignore:
      # Requires manual review and testing to update
      - dependency-name: "psutil"
        versions: [">5.9.5"]
      # Requires manual review and testing to update
      - dependency-name: "pywinctl"
        versions: [">0.0.50"]
