# Dependabot configuration
# <https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates>

version: 2
updates:
  # Bun (bun.lock)
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
      prefix-development: "chore"
      include: "scope"
    groups:
      bun:
        patterns:
          - "*"
    ignore:
      # Ignore updates to obsidian beyond 1.4.11
      - dependency-name: "obsidian"
        versions: [">1.4.11"]
      - dependency-name: "@polyipseity/obsidian"
        versions: [">1.4.11"]

  # GitHub Actions (workflow dependencies)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
      prefix-development: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"

  # Git submodules (gitmodules)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
      prefix-development: "chore"
      include: "scope"
    groups:
      gitsubmodule:
        patterns:
          - "*"
