# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files
community_bridge:
github:
  - polyipseity
issuehunt:
ko_fi:
liberapay:
open_collective:
otechie:
patreon:
tidelife:
custom:
  - https://buymeacoffee.com/polyipseity
