# <https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files>
custom:
  - https://buymeacoffee.com/polyipseity
github:
  - polyipseity
