export const
	DEFAULT_ENCODING = "utf-8",
	DISABLED_TOOLTIP = "",
	JSON_STRINGIFY_SPACE = "\t",
	NOTICE_NO_TIMEOUT = 0,
	SAVE_SETTINGS_TIMEOUT = 500,
	SI_PREFIX_SCALE = 1000,
	TERMINAL_EXIT_SUCCESS = Object.freeze([0, "SIGINT", "SIGTERM"] as const),
	TERMINAL_RESIZE_TIMEOUT = 500,
	TERMINAL_RESIZER_WATCHDOG_INTERVAL = 500
