#!/usr/bin/env sh
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
DEFAULT_BRANCH=$(git rev-parse --abbrev-ref origin/HEAD | sed 's@origin/@@')

if [ "$CURRENT_BRANCH" = "$DEFAULT_BRANCH" ]; then
    git tag --force --sign rolling --message rolling
fi
